### ISSUE TITLE
interpolation

### ISSUE THREAD

**Issue by dereyly** [IceClear/CLIP-IQA#2]
Thank you for your work
In the paper you mentioned interpolation scheme -- do you have code to interpolate embedding?
And whats best way to customize CLIP? why you choose mmedit?

**Comment by IceClear** [comment]
Hi, thanks for your interest.
The interpolation code is [here](https://github.com/IceClear/CLIP-IQA/blob/main/mmedit/models/components/clip/model.py#L69).
I choose MMEditing just because I am familiar with it. I think it should be easy to directly modify on the official CLIP code if you prefer.
[IQA-Pytorch](https://github.com/chaofengc/IQA-PyTorch) can be regarded as an example to build CLIP-IQA using BasicSR. You may take that as a reference.
